#development version of configurations
server:
  port: 8083

#  database connections
spring:
  datasource:
    url:  ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  #    hikari:
  #      pool-name: HikariCP
  #      maximum-pool-size: 5
  #      connection-timeout: 10000
  #      idle-timeout: 600000
  #      max-lifetime: 1800000
  #      validation-timeout: 1800000
  #      leak-detection-threshold: 0
  #      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    show-sql: true
  security:
    #    oauth2 configurations
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:test-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:test-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #/login/oauth2/code/google
            scope:
              - email
              - profile
              - openid
          github:
            client-id: ${GITHUB_CLIENT_ID:test-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:test-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #/login/oauth2/code/github
            scope:
              - user:email
              - read:user



#    jpa and hibernate configurations


security:
  jwt:
    secret: {YOUR_SECURITY_KEY}
    issuer: api.substring.com
    access-ttl-seconds: 3600
    refresh-ttl-seconds: 8600
    access-token-cookie-name: accessToken
    refresh-token-cookie-name: refreshToken
    cookie-secure: false
    cookie-http-only: true
    cookie-same-site: Lax
    cookie-domain:


app:
  cors:
    front-end-url: http://localhost:5173
  auth:
    frontend:
      success-redirect: ${FRONT_END_SUCCESS_REDIRECT:http://localhost:5173/oauth/success}
      failure-redirect: ${FRONT_END_FAILURE_REDIRECT:http://localhost:5173/oauth/failure}

